apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
data:
  PASSWORD: bXlfcGFzcy13b3Jk

---

#ConfigMap
apiVersion: v1
kind: ConfigMap
metadata: 
   name: app-settings
data:
  APP_MODE: staging
  TIMEOUT: "30"
---
#
apiVersion: v1
kind: Secret
metadata:
   name: tls-secret
data:
  server.crt: ZmFrZV9jZXJ0aWZpY2F0ZV9kYXRh
---

# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-service-deployment
  labels:
    app: backend-app
spec:
  replicas: 2
  selector:
      matchLabels:
          app: backend-app
  template:
      metadata:
         labels:
           app: backend-app
      spec:
        containers:
            - name: app-core 
              image: nginx:alpine
              env:
                - name: MODE
                  valueFrom:
                    configMapKeyRef:
                       name: app-settings
                       key: APP_MODE
                - name: DB_PASS
                  valueFrom:
                    secretKeyRef:
                        name: db-credentials
                        key: PASSWORD
              volumeMounts:
                - name: tls-volume
                  mountPath: /etc/ssl/certs
                  readOnly: true
        volumes:
          -  name: tls-volume
             secret:
              secretName: tls-secret
