apiVersion: v1
kind: Secret
metadata:
   name: ssh-key-secret
data:
  id_rsa: aWQtcnNhLXNlY3JldA==

---

#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
   name: volume-test-deployment
   labels:
     app: secret-volume
spec:
  replicas: 1
  selector:
     matchLabels:
        app: secret-volume
  template:
     metadata:
      labels:
        app: secret-volume
     spec:
       containers:
         - name: web
           image: nginx:alpine
           volumeMounts:
              - name: sec-vol
                mountPath: /etc/keys
                readOnly: true
       volumes:
         - name: sec-vol
           secret:
              secretName: ssh-key-secret
  
